version: '3'
services:
  image_processing:
    build: .
    environment:
      TZ: Asia/Tokyo
      GO_ENV: development
    volumes:
      - .:/go/src/
    ports:
      - 3000:3000
    privileged: true
    command: realize start
    depends_on:
      - lb
      - storage
  lb:
    build: ./docker/lb
    ports:
      - 8000:8000
  storage:
    build: ./docker/storage
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: image_processing
      MINIO_SECRET_KEY: password
